### ISSUE TITLE
What happen if server peer pretend to be a client peer?

### ISSUE THREAD

**Issue by smallswan399** [duzun/P2PEG#1]
For client-peer there is no way to know about P2PEG's internal state or about other client-peers, hence generated data is truly random and unpredictable.
But what happen if server peer pretend to be a client peer? Is it able to prevent someone own server peer node cheat the others?

**Comment by duzun** [comment]
When two P2PEG servers exchange entropy (through a request), they both are clients to each other at the same time. Hence the name "Peer to Peer".
Regardless of the nature of clients requesting my own server (P2PEG aware or not), I treat them the same: no one can be trusted!

I base on a property analysed and proven in my Masters Thesis:

The sum **c** = r<sub>1</sub>  ⊕ r<sub>2</sub> ⊕ ... ⊕ r<sub>m</sub>, where **c**, r<sub>i</sub> ∊ 𝔹<sub>k</sub> (string of bits of length k), i=1,m, is a [perfect secret](https://www.wikiwand.com/en/One-time_pad#Perfect_secrecy) if and only if there is at least one r<sub>i</sub> perfect secret and the operation ⊕ is a [cryptographic safe](https://www.wikiwand.com/en/Cryptographic_hash_function) operation.

All peers provide some r<sub>i</sub>, plus server has it's own entropy r<sub>j</sub>. All the entropy is mixed through a [Cryptographic hash function](https://www.wikiwand.com/en/Cryptographic_hash_function). 
The result is at least as unpredictable as the most unpredictable r<sub>j</sub> from the list.
In the case where one or many sources of entropy (r<sub>i</sub>) are compromised (revealed, poor crypto quality), the entropy is still good as long as not all sources are compromized.

The fact that some clients are requesting my server at unpredictable/unknown points in time also adds to the unpredictability of the whole system (think of reseeding at random intervals).
